#!/bin/sh
ssh ubuntu@43.201.18.152 <<EOF
    cd ~/seoulminer-backend
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 16.2.0
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF